name: InstaWP WordPress Testing

on:
  pull_request:
    types: [opened]

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: lincolnb17/wordpress-testing-automation@main
        with:
          INSTAWP_DOMAIN: stage.instawp.io
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_TEMPLATE_SLUG: react
          REPO_ID: 15
          INSTAWP_ACTION: create-site-template
